GlareDB/glaredb.github.io

- docs/sql-reference/system-catalog/information_schema.md
- docs/sql-reference/system-catalog/pg-catalog.md
> fix: preliminary information_schema; pg_catalog

- .markdownlint-cli2.jsonc
- cspell.json
- docs/sql-reference/sql-commands/select.md
> docs: select reference

- docs/sql-reference/sql-commands/alter-tunnel.md
> feat: alter tunnel reference

- docs/about/technical-preview.md
- index.md
> chore: oss announcement

- .markdownlint-cli2.jsonc
- _glaredb/data-types.md
- _glaredb/local.md
- _glaredb/python.md
- _glaredb/releases.md
- _glaredb/sql-commands/index.md
- _glaredb/system-catalog/index.md
- _glaredb/transactions.md
- index.md
Resolves: #76
Resolves: #99
1. Updated Offerings with links to trying locally or in Python
2. Local
3. Python w API and Example
> docs: glaredb local; glaredb-python

- _glaredb/releases.md
- _glaredb/sq-functions/csv_scan.md
- _glaredb/sq-functions/generate_series.md
- _glaredb/sq-functions/index.md
- _glaredb/sq-functions/list_schemas.md
- _glaredb/sq-functions/list_tables.md
- _glaredb/sq-functions/ndjson_scan.md
- _glaredb/sq-functions/parquet_scan.md
- _glaredb/sq-functions/read_bigquery.md
- _glaredb/sq-functions/read_mongodb.md
- _glaredb/sq-functions/read_mysql.md
- _glaredb/sq-functions/read_postgres.md
- _glaredb/sq-functions/read_snowflake.md
- _glaredb/system-catalog/glare-catalog.md
- _glaredb/system-catalog/index.md
- _glaredb/transactions.md
- cspell.json
* glare_catalog.functions
* csv_scan
* generate_series
* list_schemas
* list_tables
* ndjson_scan
* parquet_scan
* read_bigquery
* read_mongodb
* read_mysql
* read_postgres
* read_snowflake
Resolves: #86
> docs: table functions

- Gemfile.lock
- _glaredb/local.md
- _glaredb/sql-commands/select.md
> docs: add EXCLUDE and local examples

- Gemfile
- Gemfile.lock
- _sass/color_schemes/glaredb.scss
> chore: Update just the docs

- _glaredb/sq-functions/csv_scan.md
- _glaredb/sq-functions/ndjson_scan.md
- _glaredb/sq-functions/parquet_scan.md
Was a find & replace from the parquet one.
> chore: Add more documentation for ndjson_scan and csv_scan

- _glaredb/sql-commands/delete.md
Adding documentation for delete rows with or without a condition
> chore: documentation of delete rows with condition

- _glaredb/local.md
> docs: running glaredb@0.4.0

- _glaredb/sq-functions/csv_scan.md
- _glaredb/sq-functions/ndjson_scan.md
> docs: update compressed scans

- _glaredb/sql-commands/create-table.md
> fix: aliasing and casting in create table

- _glaredb/sq-functions/list_columns.md
- docs/releases/2023-september.md
- docs/releases/index.md
> doc: list_columns, misc updates and fixes

- .markdownlint-cli2.jsonc
- _glaredb/sql-commands/create-credentials.md
Closes https://github.com/GlareDB/glaredb.github.io/issues/162
> feat: Add CREATE CREDENTIALS docs

- docs/data-sources/connecting-data-sources.md
Mostly as a prototype for some style changes (and connecting more dots
for users.)
Let me know what you think!
> fix: style tweaks for data sources

- _includes/head_custom.html
Closed:
Open:
Example question:
> feat: Add docs bot to answer questions about glaredb

- docs/releases/2024-january.md
> Mention iceberg version fix

- _glaredb/sql-functions/read_excel.md
- index.md
> fix: broken links; feat: read_excel

- _glaredb/sql-functions/read_postgres.md
> fix: postgres example

- index.md
> Docs: letter → later

- introduction/installation/node_bindings.md
- introduction/installation/sign-up-for-cloud.md
Honestly, feel that great improvements were made to this...but I'm biased :-)
> feat(getting started): node.js installation

- introduction/installation/locally-cli.md
In the spirit of #235 but with its own touches and a nod to use cases and COPY TO.
> feat(getting started): cli installation

- package-lock.json
- package.json
Easier maintenance with Dependabot
> chore: pin node deps

- reference/sql-commands/create-external-database.md
- reference/sql-commands/create-table.md
> fix: missing 'exist' clauses

- reference/sql-functions/read_postgres.md
> fix(read_postgres): connection string

- Gemfile
- Gemfile.lock
- _config.yml
- index.md
- reference/sql-commands/create-credentials.md
- reference/sql-functions/parquet_scan.md
- reference/sql-functions/read_csv.md
- reference/sql-functions/read_delta.md
- reference/sql-functions/read_iceberg.md
- reference/sql-functions/read_lance.md
- reference/sql-functions/read_ndjson.md
- reference/system-catalog/glare-catalog.md
I updated all of the SQL function pages as well as any references I could find. I also added a Jekyll package to handle re-directs.
> Update all _scan functions to read_ functions and add redirects

- .markdownlint-cli2.jsonc
- cspell.json
- reference/sql-commands/copy-to.md
- reference/sql-commands/insert-into.md
I also embedded the video content for the new Delta video
> add docs for new delta functionality

- cspell.json
- introduction/installation.md
- introduction/key-concepts-in-glaredb.md
- introduction/quickstart.md
The Python and CLI steps are the same, just with commands specific to each environment.
Let me know if the environment set-up stuff for Python is adequate.
I need to do a bit more double-checking in the preview, but wanted to get this posted so you can start to review.
Currently there's a bug blocking COPY TO, but I can pull those steps out if needed.
> add quickstart doc

- introduction/r-bindings.md
Mirror of #302 that should work better with CI. 
Closes: #302
> fix(docs): improvements and corrections to r-bindings docs

- cspell.json
- tutorials/connect-in-go.md
- tutorials/join-across-data-sources-with-dbt.md
As discussed in the marketing meeting, rewrote the dbt blog post as a docs page to help with our SEO
> docs: add dbt tutorial
